#// From original forked repo
language: node_js
node_js:
  - "8"
  - "9"
services: mongodb
cache:
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run lint
  - npm test

#// From Coder Camps
# .travis.yml file
# language: node_js
# node_js:
#   - "node"
#   - "7"
# install:
#   - npm install
# script:
#   - npm test
